[build]
builder = "nixpacks"

[deploy]
startCommand = "./start-all.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "wedding-invitation"
